# Site settings
title: jekyll-swagger
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://github.com/SaranyaDandu2/SaranyaDandu2.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
